url: https://adri-7.github.io/
baseurl: /ShowcaseWebsite/

# Site settings
title: Granicare
header1: Peur des dates de péremption ?
header2: La sécurité en une application !
button: Voir plus
email: contact@granicare.io
description: "Peur des dates de péremption ?"


# Team names, titles and social links
people:
- name: Adrien
  pic: 1
  position: Head of SPA development
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Naima
  pic: 2
  position: Head of marketing
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Nathan
  pic: 3
  position: Head of consumer care
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Christina
  pic: 4
  position: Head of German department
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Aurélien
  pic: 5
  position: Head of money managment
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: github
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
